; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html[platformio]
[platformio]
default_envs = ESP32_2432S028R_ILI9341

; custom common options
[common]
build_flags =
  -D USER_SETUP_LOADED=1
  -D LV_CONF_INCLUDE_SIMPLE=1
  -include src/lv_conf.h
lib_deps_builtin =
  SPI
  Wire
lib_deps_external =
  bodmer/TFT_eSPI@^2.5.43
  paulstoffregen/XPT2046_Touchscreen
  lvgl/lvgl@^9.5.0

[env:ESP32_2432S028R_ILI9341]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; Build options
build_flags =
  ${common.build_flags}
  -include src/Setup_ESP32_2432S028R_ILI9341.h

; Library options
lib_deps =
  ${common.lib_deps_builtin}
  ${common.lib_deps_external}

[env:ESP32_2432S028R_ST7789]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; Build options
build_flags =
  ${common.build_flags}
  -include src/Setup_ESP32_2432S028R_ST7789.h

; Library options
lib_deps =
  ${common.lib_deps_builtin}
  ${common.lib_deps_external}
