; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32_2432S028R_ILI9341]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
	lvgl/lvgl@^9.5.0
build_flags =
	-D USER_SETUP_LOADED=1
  -D LV_CONF_INCLUDE_SIMPLE=1
	-include src/Setup_ESP32_2432S028R_ILI9341.h
  -include src/lv_conf.h
monitor_speed = 115200

[env:ESP32_2432S028R_ST7789]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
	lvgl/lvgl@^9.5.0
build_flags =
	-D USER_SETUP_LOADED=1
  -D LV_CONF_INCLUDE_SIMPLE=1
	-include src/Setup_ESP32_2432S028R_ST7789.h
  -include src/lv_conf.h
monitor_speed = 115200
